apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonefinal2
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: capstonefinal2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstonefinal2
    spec:
      containers:
        - image: jankes11/capstonefinal2
          imagePullPolicy: Always
          name: capstonefinal2
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: capstonefinal2
spec:
  type: LoadBalancer
  selector:
    app: capstonefinal2
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
