apiVersion: apps/v1
kind: Deployment
metadata:
  name: fincapstone
  labels:
    app: fincapstone
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: fincapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fincapstone
    spec:
      containers:
        - image: jankes11/fincapstone:final
          imagePullPolicy: Always
          name: newimage
          ports:
            - containerPort: 80
---
#Services

apiVersion: v1
kind: Service
metadata:
  name: fincapstone
  labels:
    app: fincapstone
spec:
  type: LoadBalancer
  selector:
    app: fincapstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP