apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonefinal
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: capstonefinal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstonefinal
    spec:
      containers:
        - image: jankes11/capstonefinal
          imagePullPolicy: Always
          name: capstonefinal
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: capstonefinal
spec:
  type: LoadBalancer
  selector:
    app: capstonefinal
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
