apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonefnl
  labels:
    app: capstonefnl
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: capstonefnl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstonefnl
    spec:
      containers:
        - image: jankes11/capstonefnl:final
          imagePullPolicy: Always
          name: newimage
          ports:
            - containerPort: 80
---
#Services

apiVersion: v1
kind: Service
metadata:
  name: capstonefnl
  labels:
    app: capstonefnl
spec:
  type: LoadBalancer
  selector:
    app: capstonefnl
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP